version: "3.9"

services:
  # 1. Your Python Notification App
  notification-app:
    build: .
    container_name: notification_service
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  # 2. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always


  worker:
    build: .
    command: python worker.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

volumes:
  rabbitmq_data:
